# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_configurable_user_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurableuser',
            options={'verbose_name': 'User', 'verbose_name_plural': "User's"},
        ),
        migrations.RemoveField(
            model_name='configurableuser',
            name='runt',
        ),
        migrations.AddField(
            model_name='configurableuser',
            name='second_email',
            field=models.EmailField(default='henk@lol.stom', max_length=254, verbose_name='Another email'),
            preserve_default=False,
        ),
    ]
